services:
  neo4j:
    image: neo4j:5.23.0-enterprise
    container_name: neo4j
    ports:
      - 7474:7474
      - 7687:7687
    environment:
      - NEO4J_ACCEPT_LICENSE_AGREEMENT=yes
      - NEO4J_AUTH=neo4j/password
      - NEO4J_PLUGINS=["apoc","apoc-extended"]
    volumes:
      - "./driver/mssql-jdbc-12.8.1.jre11.jar:/plugins/mssql-jdbc-driver.jar"
      - "./conf/apoc.conf:/conf/apoc.conf"
  sql-server:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: sqlserver
    environment:
      - ACCEPT_EULA=Y
      - MSSQL_SA_PASSWORD=npaEzszSALRH5q56372zGJ
      - MSSQL_PID=Express
    healthcheck:
      test: "/opt/mssql-tools18/bin/sqlcmd -S localhost -U sa -P npaEzszSALRH5q56372zGJ -Q 'SELECT 1' -C || exit 1"
      interval: 10s
      retries: 5
      start_period: 30s
      timeout: 5s
    ports:
      - 1433:1433
    volumes:
      - "./sql/people_data.xml:/sql/people_data.xml"
  sql-init:
    image: ikwattro/sqlcmd:slim
    container_name: init-sqlserver
    depends_on:
      sql-server:
        condition: service_healthy
    command: ["sqlcmd", "-S", "sqlserver", "-U", "sa", "-P", "npaEzszSALRH5q56372zGJ", "-i", "/sql/init.sql", "-C"]
    volumes:
      - "./sql/init.sql:/sql/init.sql"